### PR TITLE
Add some more code cleanup

### PR DESCRIPTION
**Pull request by xvilo**
- you are now able to create a request
- you are now able to post a response

### CODE REVIEW

**Comment by xvilo** [comment]
Currently added some more, this completely fixes offerForm (for now) with form validation server side. We should do this to all forms

**Comment by ferrydeboer** [comment]
I am testing this, but it only shows one error for the first field that has the error. I doubt this is intended behaviour since all the errors are reported back.

**Review by ferrydeboer — COMMENTED** [review]
I am testing this, but it only shows one error for the first field that has the error. I doubt this is intended behaviour since all the errors are reported back to the twig template.

Edit: Looks like I'm messing something up with git when doing this locally.

**Comment by xvilo** [comment]
Jup, this should just work fine with the stuff I tested here :)

**Pull request closed without merging**
