### PR TITLE
Add php linter

### PR DESCRIPTION
**Pull request by xvilo**
- This adds linting for all PHP files, so they have a clear and fine code style. Output on current master: https://github.com/xvilo/heldnodig-site/runs/518519406?check_suite_focus=true
- Changed all the files to "fix" them for the linter.
- Changed `offerForm.php` and `requestForm.php` as they had invalid PHP syntax
- Now everything is green, please keep it so: https://github.com/xvilo/heldnodig-site/runs/518528364?check_suite_focus=true

### CODE REVIEW

**Comment by ferrydeboer** [comment]
Always fun, reviewing whitespace changes. 😆But can you fix the conflict @milovanderlinden that are due to other changes.

**Comment by xvilo** [comment]
@ferrydeboer fixed them

**Comment by ferrydeboer** [comment]
Love this!

**Comment by xvilo** [comment]
high five

**Comment by ferrydeboer** [comment]
🤣

**Pull request merged**
